# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - AlertsFunctionGrani

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze > requirements.txt  # This ensures all dependencies are captured

      - name: Create function folders if not exist
        run: |
          mkdir -p AlertsFunctionGrani
          mkdir -p insert_new_alert_grani
          mkdir -p get_all_alerts
          mkdir -p shared_code

      - name: Clean up unnecessary files
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf __pycache__
          rm -rf .pytest_cache
          find . -type d -name "__pycache__" -exec rm -r {} +

      - name: Zip artifact for deployment
        run: |
          cp requirements.txt
          zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_25A6752115FD427CA6F434FC29D9562E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2575A1B6B2D04A0997FB3D4736068E2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_694FC964507A4749A9DC27079893A4B3 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'AlertsFunctionGrani'
          slot-name: 'Production'
          package: '.'
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          enable-dependency-installation: true